const fs = require('fs');
const path = require('path');

const schemaDir = 
path.join(__dirname, 'prisma');
const outputSchema = path.join(schemaDir, 'schema.prisma');

try {
    // delete generated schema file so that it doesn't concatenate itself
    fs.unlinkSync(outputSchema);
} catch (error) {}

const schemaFiles = fs.readdirSync(schemaDir).filter(file => file.endsWith('.prisma'));

let combinedSchema = fs.readFileSync(path.join(schemaDir, "schema-template.txt"));
schemaFiles.forEach(filename => {
    const filePath = path.join(schemaDir, filename);
    const fileContent = fs.readFileSync(filePath);
    combinedSchema += fileContent + '\n';
});

fs.writeFileSync(outputSchema, "// generated by concatenate-schemas.js\n" + combinedSchema, { flag: 'w'});
console.log('dunn');
